stages:
  - build
  - test

.build: &build
  image: debian
  stage: build
  script:
    - apt update && apt install -y debhelper-compat config-package-dev python3-pip $EXTRA_PKG
    - dpkg-buildpackage -uc -us --host-arch $ARCH
    - mv ../*.deb ./
  artifacts:
    paths:
      - "*.deb"

build-amd64:
  <<: *build
  variables:
    ARCH: amd64

build-arm64:
  <<: *build
  variables:
    ARCH: arm64
    EXTRA_PKG: binutils-aarch64-linux-gnu

test-install:
  image: debian:testing
  stage: test
  dependencies:
    - build-amd64
  before_script:
    - apt update && apt install -y gnokii-cli python3 openssl systemd-standalone-sysusers
  script:
    - dpkg -i eat-my-sms_*_amd64.deb
