[DEFAULT]
pin = 0000
poll_interval = 5

webhook_url = https://dashboard.pescheck.io/webhook
# Add a static value to the 'extra' field in every webhook payload
# webhook_extra = foo

# Override settings for specific devices
# [ttyACM0]
# poll_interval = 3
# webhook_url = https://dashboard.pescheck.io/other-webhook
