[DEFAULT]
pin = 0000
poll_interval = 5

webhook_url = https://example.com/webhook
# Add a static value to the 'extra' field in every webhook payload
# webhook_extra = production

# Override settings for specific devices
# [ttyUSB0]
# poll_interval = 3
# webhook_url = https://example.com/other-webhook
# metrics_port = 8080
